## Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

# Python Object

Type of the data (integer, float, Python object, etc.)

Size of the data (how many bytes is in e.g. the integer)

Byte order of the data (little-endian or big-endian)

If the data type is structured data type, an aggregate of other data types, (e.g., describing an array item consisting of an integer and a float),

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4])

print(a)

print(np.arange(10))

[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


***Why it useful :*** Memory-efficient container that provides fast numerical operation

In [2]:
# python lists

L = range(10)
print(L)

lis = [ i ** 2 for i in L]

lis

range(0, 10)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [3]:
a = np.arange(10)
a ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

# Creating Array

In [4]:
# 1 # D

a = np.array([1, 2, 3, 4])

a

array([1, 2, 3, 4])

In [6]:
# print dimensions

a.ndim

1

In [7]:
# shape
a.shape

(4,)

In [8]:
# length
len(a)

# note : simple function in python

4

In [12]:
# 2--D , and 3--D

b = np.array([[1, 2, 3],[5, 6, 7]])

b

array([[1, 2, 3],
       [5, 6, 7]])

In [17]:
b.ndim

2

In [18]:
b.shape

(2, 3)

In [19]:
len(b)# Accessing elements in a numpy array

2

In [23]:
c = np.array([[[1, 2,], [3, 4]], [[4, 5, ], [6,7]], [[4, 5, ], [6,7]]])

c

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]],

       [[4, 5],
        [6, 7]]])

In [24]:
c.ndim

3

In [25]:
c.shape

(3, 2, 2)

# Function for creating arrays

In [26]:
# using array function

# array is an array-valued version of the built-in  python range function

a = np.arange(10)  # 0......n-1

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b = np.arange(4, 30, 3)  #start, end (exclusive), step

b

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28])

In [29]:
# using linespace
a = np.linspace(0, 1, 5)  # start, end, number of points

a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
# common Array
a = np.ones((6, 6))

a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [33]:
b =np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
c = np.eye(8) # Return a 2D--array with ones on the diagonal and zeros elsewhere

c

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [36]:
d = np.eye(3, 3)  #3 is number of rows, 2 is number of columns, index of diagonal start with 0

d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# Create array using diag function

a = np.diag([1, 2, 7, 4, 9]) # construct a diagonal array

a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 9]])

In [38]:
np.diag(a) # Extract the diagonal elements of array a


array([1, 2, 7, 4, 9])

In [39]:
# Create array using random module

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

a = np.random.rand(3, 3)

a

array([[0.77749478, 0.15084666, 0.7080818 ],
       [0.3714399 , 0.4973659 , 0.35521872],
       [0.2788309 , 0.9880538 , 0.57206668]])

In [42]:
b = np.random.randn(4)  # Create an array of the given shape and populate it with random samples from a normal distribution

b

array([-0.36439966,  0.00392484,  1.6439618 , -0.75769389])